//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Dothan.ProjectInfo
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SettleEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SettleEntities object using the connection string found in the 'SettleEntities' section of the application configuration file.
        /// </summary>
        public SettleEntities() : base("name=SettleEntities", "SettleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SettleEntities object.
        /// </summary>
        public SettleEntities(string connectionString) : base(connectionString, "SettleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SettleEntities object.
        /// </summary>
        public SettleEntities(EntityConnection connection) : base(connection, "SettleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_project_info> tb_project_info
        {
            get
            {
                if ((_tb_project_info == null))
                {
                    _tb_project_info = base.CreateObjectSet<tb_project_info>("tb_project_info");
                }
                return _tb_project_info;
            }
        }
        private ObjectSet<tb_project_info> _tb_project_info;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_security_store_acc> tb_security_store_acc
        {
            get
            {
                if ((_tb_security_store_acc == null))
                {
                    _tb_security_store_acc = base.CreateObjectSet<tb_security_store_acc>("tb_security_store_acc");
                }
                return _tb_security_store_acc;
            }
        }
        private ObjectSet<tb_security_store_acc> _tb_security_store_acc;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_money_store> tb_money_store
        {
            get
            {
                if ((_tb_money_store == null))
                {
                    _tb_money_store = base.CreateObjectSet<tb_money_store>("tb_money_store");
                }
                return _tb_money_store;
            }
        }
        private ObjectSet<tb_money_store> _tb_money_store;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_project_info EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_project_info(tb_project_info tb_project_info)
        {
            base.AddObject("tb_project_info", tb_project_info);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_security_store_acc EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_security_store_acc(tb_security_store_acc tb_security_store_acc)
        {
            base.AddObject("tb_security_store_acc", tb_security_store_acc);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_money_store EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_money_store(tb_money_store tb_money_store)
        {
            base.AddObject("tb_money_store", tb_money_store);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SettleModel", Name="tb_money_store")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_money_store : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_money_store object.
        /// </summary>
        /// <param name="idx">Initial value of the idx property.</param>
        /// <param name="xmdm">Initial value of the xmdm property.</param>
        /// <param name="zcdy">Initial value of the zcdy property.</param>
        /// <param name="zhdm">Initial value of the zhdm property.</param>
        public static tb_money_store Createtb_money_store(global::System.Int64 idx, global::System.Int32 xmdm, global::System.String zcdy, global::System.String zhdm)
        {
            tb_money_store tb_money_store = new tb_money_store();
            tb_money_store.idx = idx;
            tb_money_store.xmdm = xmdm;
            tb_money_store.zcdy = zcdy;
            tb_money_store.zhdm = zhdm;
            return tb_money_store;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idx
        {
            get
            {
                return _idx;
            }
            set
            {
                if (_idx != value)
                {
                    OnidxChanging(value);
                    ReportPropertyChanging("idx");
                    _idx = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idx");
                    OnidxChanged();
                }
            }
        }
        private global::System.Int64 _idx;
        partial void OnidxChanging(global::System.Int64 value);
        partial void OnidxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> item_id
        {
            get
            {
                return _item_id;
            }
            set
            {
                Onitem_idChanging(value);
                ReportPropertyChanging("item_id");
                _item_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("item_id");
                Onitem_idChanged();
            }
        }
        private Nullable<global::System.Int64> _item_id;
        partial void Onitem_idChanging(Nullable<global::System.Int64> value);
        partial void Onitem_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 xmdm
        {
            get
            {
                return _xmdm;
            }
            set
            {
                OnxmdmChanging(value);
                ReportPropertyChanging("xmdm");
                _xmdm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("xmdm");
                OnxmdmChanged();
            }
        }
        private global::System.Int32 _xmdm;
        partial void OnxmdmChanging(global::System.Int32 value);
        partial void OnxmdmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zcdy
        {
            get
            {
                return _zcdy;
            }
            set
            {
                OnzcdyChanging(value);
                ReportPropertyChanging("zcdy");
                _zcdy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("zcdy");
                OnzcdyChanged();
            }
        }
        private global::System.String _zcdy;
        partial void OnzcdyChanging(global::System.String value);
        partial void OnzcdyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zhdm
        {
            get
            {
                return _zhdm;
            }
            set
            {
                OnzhdmChanging(value);
                ReportPropertyChanging("zhdm");
                _zhdm = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("zhdm");
                OnzhdmChanged();
            }
        }
        private global::System.String _zhdm;
        partial void OnzhdmChanging(global::System.String value);
        partial void OnzhdmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> policy_id
        {
            get
            {
                return _policy_id;
            }
            set
            {
                Onpolicy_idChanging(value);
                ReportPropertyChanging("policy_id");
                _policy_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("policy_id");
                Onpolicy_idChanged();
            }
        }
        private Nullable<global::System.Int32> _policy_id;
        partial void Onpolicy_idChanging(Nullable<global::System.Int32> value);
        partial void Onpolicy_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> order_id
        {
            get
            {
                return _order_id;
            }
            set
            {
                Onorder_idChanging(value);
                ReportPropertyChanging("order_id");
                _order_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_id");
                Onorder_idChanged();
            }
        }
        private Nullable<global::System.Int32> _order_id;
        partial void Onorder_idChanging(Nullable<global::System.Int32> value);
        partial void Onorder_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> trade_id
        {
            get
            {
                return _trade_id;
            }
            set
            {
                Ontrade_idChanging(value);
                ReportPropertyChanging("trade_id");
                _trade_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("trade_id");
                Ontrade_idChanged();
            }
        }
        private Nullable<global::System.Int32> _trade_id;
        partial void Ontrade_idChanging(Nullable<global::System.Int32> value);
        partial void Ontrade_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> security_id
        {
            get
            {
                return _security_id;
            }
            set
            {
                Onsecurity_idChanging(value);
                ReportPropertyChanging("security_id");
                _security_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("security_id");
                Onsecurity_idChanged();
            }
        }
        private Nullable<global::System.Int32> _security_id;
        partial void Onsecurity_idChanging(Nullable<global::System.Int32> value);
        partial void Onsecurity_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> money
        {
            get
            {
                return _money;
            }
            set
            {
                OnmoneyChanging(value);
                ReportPropertyChanging("money");
                _money = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("money");
                OnmoneyChanged();
            }
        }
        private Nullable<global::System.Double> _money;
        partial void OnmoneyChanging(Nullable<global::System.Double> value);
        partial void OnmoneyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String date_str
        {
            get
            {
                return _date_str;
            }
            set
            {
                Ondate_strChanging(value);
                ReportPropertyChanging("date_str");
                _date_str = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("date_str");
                Ondate_strChanged();
            }
        }
        private global::System.String _date_str;
        partial void Ondate_strChanging(global::System.String value);
        partial void Ondate_strChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> froze
        {
            get
            {
                return _froze;
            }
            set
            {
                OnfrozeChanging(value);
                ReportPropertyChanging("froze");
                _froze = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("froze");
                OnfrozeChanged();
            }
        }
        private Nullable<global::System.Int32> _froze;
        partial void OnfrozeChanging(Nullable<global::System.Int32> value);
        partial void OnfrozeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String froze_date
        {
            get
            {
                return _froze_date;
            }
            set
            {
                Onfroze_dateChanging(value);
                ReportPropertyChanging("froze_date");
                _froze_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("froze_date");
                Onfroze_dateChanged();
            }
        }
        private global::System.String _froze_date;
        partial void Onfroze_dateChanging(global::System.String value);
        partial void Onfroze_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String melt_date
        {
            get
            {
                return _melt_date;
            }
            set
            {
                Onmelt_dateChanging(value);
                ReportPropertyChanging("melt_date");
                _melt_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("melt_date");
                Onmelt_dateChanged();
            }
        }
        private global::System.String _melt_date;
        partial void Onmelt_dateChanging(global::System.String value);
        partial void Onmelt_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> froze_reason
        {
            get
            {
                return _froze_reason;
            }
            set
            {
                Onfroze_reasonChanging(value);
                ReportPropertyChanging("froze_reason");
                _froze_reason = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("froze_reason");
                Onfroze_reasonChanged();
            }
        }
        private Nullable<global::System.Int32> _froze_reason;
        partial void Onfroze_reasonChanging(Nullable<global::System.Int32> value);
        partial void Onfroze_reasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String froze_source
        {
            get
            {
                return _froze_source;
            }
            set
            {
                Onfroze_sourceChanging(value);
                ReportPropertyChanging("froze_source");
                _froze_source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("froze_source");
                Onfroze_sourceChanged();
            }
        }
        private global::System.String _froze_source;
        partial void Onfroze_sourceChanging(global::System.String value);
        partial void Onfroze_sourceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SettleModel", Name="tb_project_info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_project_info : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_project_info object.
        /// </summary>
        /// <param name="idx">Initial value of the idx property.</param>
        /// <param name="xmdm">Initial value of the xmdm property.</param>
        /// <param name="zcdy">Initial value of the zcdy property.</param>
        /// <param name="zhdm">Initial value of the zhdm property.</param>
        public static tb_project_info Createtb_project_info(global::System.Int64 idx, global::System.Int32 xmdm, global::System.String zcdy, global::System.String zhdm)
        {
            tb_project_info tb_project_info = new tb_project_info();
            tb_project_info.idx = idx;
            tb_project_info.xmdm = xmdm;
            tb_project_info.zcdy = zcdy;
            tb_project_info.zhdm = zhdm;
            return tb_project_info;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idx
        {
            get
            {
                return _idx;
            }
            set
            {
                if (_idx != value)
                {
                    OnidxChanging(value);
                    ReportPropertyChanging("idx");
                    _idx = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idx");
                    OnidxChanged();
                }
            }
        }
        private global::System.Int64 _idx;
        partial void OnidxChanging(global::System.Int64 value);
        partial void OnidxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 xmdm
        {
            get
            {
                return _xmdm;
            }
            set
            {
                OnxmdmChanging(value);
                ReportPropertyChanging("xmdm");
                _xmdm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("xmdm");
                OnxmdmChanged();
            }
        }
        private global::System.Int32 _xmdm;
        partial void OnxmdmChanging(global::System.Int32 value);
        partial void OnxmdmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String project_name
        {
            get
            {
                return _project_name;
            }
            set
            {
                Onproject_nameChanging(value);
                ReportPropertyChanging("project_name");
                _project_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("project_name");
                Onproject_nameChanged();
            }
        }
        private global::System.String _project_name;
        partial void Onproject_nameChanging(global::System.String value);
        partial void Onproject_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zcdy
        {
            get
            {
                return _zcdy;
            }
            set
            {
                OnzcdyChanging(value);
                ReportPropertyChanging("zcdy");
                _zcdy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("zcdy");
                OnzcdyChanged();
            }
        }
        private global::System.String _zcdy;
        partial void OnzcdyChanging(global::System.String value);
        partial void OnzcdyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zhdm
        {
            get
            {
                return _zhdm;
            }
            set
            {
                OnzhdmChanging(value);
                ReportPropertyChanging("zhdm");
                _zhdm = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("zhdm");
                OnzhdmChanged();
            }
        }
        private global::System.String _zhdm;
        partial void OnzhdmChanging(global::System.String value);
        partial void OnzhdmChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SettleModel", Name="tb_security_store_acc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_security_store_acc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_security_store_acc object.
        /// </summary>
        /// <param name="idx">Initial value of the idx property.</param>
        /// <param name="xmdm">Initial value of the xmdm property.</param>
        /// <param name="zcdy">Initial value of the zcdy property.</param>
        /// <param name="zhdm">Initial value of the zhdm property.</param>
        /// <param name="policy_id">Initial value of the policy_id property.</param>
        public static tb_security_store_acc Createtb_security_store_acc(global::System.Int64 idx, global::System.Int32 xmdm, global::System.String zcdy, global::System.String zhdm, global::System.Int32 policy_id)
        {
            tb_security_store_acc tb_security_store_acc = new tb_security_store_acc();
            tb_security_store_acc.idx = idx;
            tb_security_store_acc.xmdm = xmdm;
            tb_security_store_acc.zcdy = zcdy;
            tb_security_store_acc.zhdm = zhdm;
            tb_security_store_acc.policy_id = policy_id;
            return tb_security_store_acc;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idx
        {
            get
            {
                return _idx;
            }
            set
            {
                if (_idx != value)
                {
                    OnidxChanging(value);
                    ReportPropertyChanging("idx");
                    _idx = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idx");
                    OnidxChanged();
                }
            }
        }
        private global::System.Int64 _idx;
        partial void OnidxChanging(global::System.Int64 value);
        partial void OnidxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 xmdm
        {
            get
            {
                return _xmdm;
            }
            set
            {
                OnxmdmChanging(value);
                ReportPropertyChanging("xmdm");
                _xmdm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("xmdm");
                OnxmdmChanged();
            }
        }
        private global::System.Int32 _xmdm;
        partial void OnxmdmChanging(global::System.Int32 value);
        partial void OnxmdmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zcdy
        {
            get
            {
                return _zcdy;
            }
            set
            {
                OnzcdyChanging(value);
                ReportPropertyChanging("zcdy");
                _zcdy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("zcdy");
                OnzcdyChanged();
            }
        }
        private global::System.String _zcdy;
        partial void OnzcdyChanging(global::System.String value);
        partial void OnzcdyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zhdm
        {
            get
            {
                return _zhdm;
            }
            set
            {
                OnzhdmChanging(value);
                ReportPropertyChanging("zhdm");
                _zhdm = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("zhdm");
                OnzhdmChanged();
            }
        }
        private global::System.String _zhdm;
        partial void OnzhdmChanging(global::System.String value);
        partial void OnzhdmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 policy_id
        {
            get
            {
                return _policy_id;
            }
            set
            {
                Onpolicy_idChanging(value);
                ReportPropertyChanging("policy_id");
                _policy_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("policy_id");
                Onpolicy_idChanged();
            }
        }
        private global::System.Int32 _policy_id;
        partial void Onpolicy_idChanging(global::System.Int32 value);
        partial void Onpolicy_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String date_str
        {
            get
            {
                return _date_str;
            }
            set
            {
                Ondate_strChanging(value);
                ReportPropertyChanging("date_str");
                _date_str = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("date_str");
                Ondate_strChanged();
            }
        }
        private global::System.String _date_str;
        partial void Ondate_strChanging(global::System.String value);
        partial void Ondate_strChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String security_id
        {
            get
            {
                return _security_id;
            }
            set
            {
                Onsecurity_idChanging(value);
                ReportPropertyChanging("security_id");
                _security_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("security_id");
                Onsecurity_idChanged();
            }
        }
        private global::System.String _security_id;
        partial void Onsecurity_idChanging(global::System.String value);
        partial void Onsecurity_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> long_num
        {
            get
            {
                return _long_num;
            }
            set
            {
                Onlong_numChanging(value);
                ReportPropertyChanging("long_num");
                _long_num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("long_num");
                Onlong_numChanged();
            }
        }
        private Nullable<global::System.Double> _long_num;
        partial void Onlong_numChanging(Nullable<global::System.Double> value);
        partial void Onlong_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> short_num
        {
            get
            {
                return _short_num;
            }
            set
            {
                Onshort_numChanging(value);
                ReportPropertyChanging("short_num");
                _short_num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("short_num");
                Onshort_numChanged();
            }
        }
        private Nullable<global::System.Double> _short_num;
        partial void Onshort_numChanging(Nullable<global::System.Double> value);
        partial void Onshort_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> froze_num
        {
            get
            {
                return _froze_num;
            }
            set
            {
                Onfroze_numChanging(value);
                ReportPropertyChanging("froze_num");
                _froze_num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("froze_num");
                Onfroze_numChanged();
            }
        }
        private Nullable<global::System.Double> _froze_num;
        partial void Onfroze_numChanging(Nullable<global::System.Double> value);
        partial void Onfroze_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> hedge_num
        {
            get
            {
                return _hedge_num;
            }
            set
            {
                Onhedge_numChanging(value);
                ReportPropertyChanging("hedge_num");
                _hedge_num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hedge_num");
                Onhedge_numChanged();
            }
        }
        private Nullable<global::System.Double> _hedge_num;
        partial void Onhedge_numChanging(Nullable<global::System.Double> value);
        partial void Onhedge_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> long_balance
        {
            get
            {
                return _long_balance;
            }
            set
            {
                Onlong_balanceChanging(value);
                ReportPropertyChanging("long_balance");
                _long_balance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("long_balance");
                Onlong_balanceChanged();
            }
        }
        private Nullable<global::System.Double> _long_balance;
        partial void Onlong_balanceChanging(Nullable<global::System.Double> value);
        partial void Onlong_balanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> short_balance
        {
            get
            {
                return _short_balance;
            }
            set
            {
                Onshort_balanceChanging(value);
                ReportPropertyChanging("short_balance");
                _short_balance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("short_balance");
                Onshort_balanceChanged();
            }
        }
        private Nullable<global::System.Double> _short_balance;
        partial void Onshort_balanceChanging(Nullable<global::System.Double> value);
        partial void Onshort_balanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> froze_balance
        {
            get
            {
                return _froze_balance;
            }
            set
            {
                Onfroze_balanceChanging(value);
                ReportPropertyChanging("froze_balance");
                _froze_balance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("froze_balance");
                Onfroze_balanceChanged();
            }
        }
        private Nullable<global::System.Double> _froze_balance;
        partial void Onfroze_balanceChanging(Nullable<global::System.Double> value);
        partial void Onfroze_balanceChanged();

        #endregion
    
    }

    #endregion
    
}
